# Generated by Django 4.1.6 on 2023-03-07 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Controller",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "controller_type",
                    models.CharField(max_length=10, verbose_name="Тип контроллера"),
                ),
                (
                    "serial_number",
                    models.PositiveIntegerField(
                        unique=True, verbose_name="Серийный номер контроллера"
                    ),
                ),
                (
                    "controller_activity",
                    models.CharField(
                        choices=[("1", "active"), ("0", "desactive")],
                        max_length=1,
                        verbose_name="активность контроллера",
                    ),
                ),
                (
                    "controller_online",
                    models.CharField(
                        choices=[("1", "online"), ("0", "offline")],
                        default="0",
                        max_length=1,
                        verbose_name="режим онлайн контроллера",
                    ),
                ),
                (
                    "controller_mode",
                    models.CharField(
                        choices=[
                            ("0", "norma"),
                            ("1", "block"),
                            ("2", "free"),
                            ("3", "waiting for free passage"),
                        ],
                        max_length=1,
                        verbose_name="режим работы контроллера",
                    ),
                ),
                (
                    "data_settings_zone",
                    models.JSONField(
                        default=dict,
                        editable=False,
                        verbose_name="настройки зон контроллера",
                    ),
                ),
                (
                    "other_data",
                    models.JSONField(
                        default=dict, editable=False, verbose_name="остальные настройки"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event", models.PositiveIntegerField(verbose_name="событие")),
                ("card", models.CharField(max_length=15, verbose_name="номер карты")),
                ("time", models.CharField(max_length=50, verbose_name="время события")),
                ("flag", models.PositiveIntegerField(verbose_name="флаг события")),
                (
                    "data_event",
                    models.JSONField(
                        verbose_name="дополнительная информация о событиии"
                    ),
                ),
                (
                    "controller",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="app_controller.controller",
                    ),
                ),
            ],
        ),
    ]
