# Generated by Django 4.1.6 on 2023-03-28 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("app_skud", "0001_initial"),
        ("app_controller", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="controller",
            name="checkpoint",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="app_skud.checkpoint",
            ),
        ),
    ]
