# Generated by Django 4.1.6 on 2023-02-14 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_skud', '0006_alter_monitorcheckaccess_controller_and_more'),
        ('app_controller', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='controller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_controller.controller'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_initiator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_skud.staffs'),
        ),
    ]
