# Generated by Django 4.1.6 on 2023-02-10 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_skud', '0002_alter_monitorcheckaccess_controller_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitorcheckaccess',
            name='data_monitor',
            field=models.JSONField(default=dict, editable=False, verbose_name='хранилище экземпляра'),
        ),
    ]
