# Generated by Django 4.1.6 on 2023-02-10 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_skud', '0003_monitorcheckaccess_data_monitor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffs',
            name='car_number',
            field=models.CharField(blank=True, help_text='Поле ввода номера машины сотрудника', max_length=10, verbose_name='Номер машины'),
        ),
    ]
