# Generated by Django 4.1.6 on 2023-02-13 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_skud', '0004_alter_staffs_car_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffs',
            name='employee_photo',
            field=models.ImageField(blank=True, upload_to='images/%Y-%m-%d/', verbose_name='Фото'),
        ),
    ]
