version: "3.7"


services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "8000:8000"
    entrypoint:
      - ./entrypoint.sh
    expose:
      - 8000
    depends_on:
      - postgres
    networks:
      - djangonetwork

  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    env_file:
      - .env
    command: -p ${POSTGRES_PORT}
    networks:
      - djangonetwork

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web
   

networks:
    djangonetwork:
        driver: bridge